// Code generated by gen; DO NOT EDIT.
package model

import (
	"graphql-project/interface/model"

	"github.com/jackc/pgx/v5"
)

func (review *Review) Table() string {
	return "reviews"
}

func (review *Review) Field(property string) string {
	switch property {
	case "id":
		return "id"
	case "createdAt":
		return "createdAt"
	case "reviewer":
		return "reviewer"
	case "product":
		return "productId"
	case "rating":
		return "rating"
	case "body":
		return "body"
	case "deletedAt":
		return "deletedAt"
	default:
		return ""
	}
}

func (review *Review) Fields() []string {
	return []string{
		"id", "createdAt", "reviewer", "productId", "rating", "body", "deletedAt",
	}
}

func (review *Review) Identity() string {
	return "id"
}

func (review *Review) ScanRow(rows pgx.Rows) (int64, bool) {
	values := rows.RawValues()
	var ordinality int64 = 0
	empty := true
	for i, fieldDesc := range rows.FieldDescriptions() {
		v := value(values[i])
		switch fieldDesc.Name {
		case "ordinality":
			ordinality = v.Int64()
		case "id":
			if v != nil {
				review.ID = v.Int64()
				empty = false
			}
		case "createdAt":
			if v != nil {
				review.CreatedAt = v.Time()
				empty = false
			}
		case "reviewer":
			if v != nil {
				review.Reviewer = v.String()
				empty = false
			}
		case "productId":
			if v != nil {
				review.ProductId = v.Int64()
				empty = false
			}
		case "rating":
			if v != nil {
				review.Rating = v.Int32()
				empty = false
			}
		case "body":
			if v != nil {
				review.Body = v.String()
				empty = false
			}
		case "deletedAt":
			if v != nil {
				n := v.Time()
				review.DeletedAt = &n
				empty = false
			}
		}
	}
	return ordinality, empty
}

type Reviews []Review

func (Reviews *Reviews) NewEntity() model.Entity {
	return &Review{}
}

func (Reviews *Reviews) Add(entity model.Entity) {
	review := entity.(*Review)
	*Reviews = append(*Reviews, *review)
}

func (review *Review) getReviewer() any {
	return (review.Reviewer)
}

func (review *Review) getProductId() any {
	return (review.ProductId)
}

func (review *Review) getRating() any {
	return (review.Rating)
}

func (review *Review) getBody() any {
	return (review.Body)
}

func (review *Review) NewEntity() model.Entity {
	return &Review{}
}

func (review *Review) EnumerateFields(f func(name string, value any)) {
	f("reviewer", review.getReviewer())
	f("productId", review.getProductId())
	f("rating", review.getRating())
	f("body", review.getBody())
}

type ReviewInput struct {
	Reviewer  NullString
	ProductId NullBigInt
	Rating    NullInt
	Body      NullString
}

func (review *ReviewInput) NewEntity() model.Entity {
	return &Review{}
}

func (review *ReviewInput) EnumerateFields(f func(name string, value any)) {
	if review.Reviewer.State != None {
		f("reviewer", review.Reviewer)
	}
	if review.ProductId.State != None {
		f("productId", review.ProductId)
	}
	if review.Rating.State != None {
		f("rating", review.Rating)
	}
	if review.Body.State != None {
		f("body", review.Body)
	}
}
