// Code generated by gen; DO NOT EDIT.
package model

import (
	"graphql-project/interface/model"

	"github.com/jackc/pgx/v5"
)

func (user *User) Table() string {
	return "users"
}

func (user *User) Field(property string) string {
	switch property {
	case "id":
		return "id"
	case "createdAt":
		return "createdAt"
	case "name":
		return "name"
	case "email":
		return "email"
	case "address":
		return "address"
	case "city":
		return "city"
	case "state":
		return "state"
	case "zip":
		return "zip"
	case "birthDate":
		return "birthDate"
	case "latitude":
		return "latitude"
	case "longitude":
		return "longitude"
	case "password":
		return "password"
	case "source":
		return "source"
	case "deletedAt":
		return "deletedAt"
	case "role":
		return "role"
	default:
		return ""
	}
}

func (user *User) Fields() []string {
	return []string{
		"id", "createdAt", "name", "email", "address", "city", "state", "zip", "birthDate", "latitude", "longitude", "password", "source", "deletedAt", "role",
	}
}

func (user *User) Identity() string {
	return "id"
}

func (user *User) ScanRow(rows pgx.Rows) (int64, bool) {
	values := rows.RawValues()
	var ordinality int64 = 0
	empty := true
	for i, fieldDesc := range rows.FieldDescriptions() {
		v := value(values[i])
		switch fieldDesc.Name {
		case "ordinality":
			ordinality = v.Int64()
		case "id":
			if v != nil {
				user.ID = v.Int64()
				empty = false
			}
		case "createdAt":
			if v != nil {
				user.CreatedAt = v.Time()
				empty = false
			}
		case "name":
			if v != nil {
				user.Name = v.String()
				empty = false
			}
		case "email":
			if v != nil {
				user.Email = v.String()
				empty = false
			}
		case "address":
			if v != nil {
				user.Address = v.String()
				empty = false
			}
		case "city":
			if v != nil {
				user.City = v.String()
				empty = false
			}
		case "state":
			if v != nil {
				user.State = v.String()
				empty = false
			}
		case "zip":
			if v != nil {
				user.Zip = v.String()
				empty = false
			}
		case "birthDate":
			if v != nil {
				user.BirthDate = v.Date()
				empty = false
			}
		case "latitude":
			if v != nil {
				user.Latitude = v.Float64()
				empty = false
			}
		case "longitude":
			if v != nil {
				user.Longitude = v.Float64()
				empty = false
			}
		case "password":
			if v != nil {
				user.Password = v.String()
				empty = false
			}
		case "source":
			if v != nil {
				user.Source = v.String()
				empty = false
			}
		case "deletedAt":
			if v != nil {
				n := v.Time()
				user.DeletedAt = &n
				empty = false
			}
		case "role":
			if v != nil {
				user.Role = v.Role()
				empty = false
			}
		}
	}
	return ordinality, empty
}

type Users []User

func (Users *Users) NewEntity() model.Entity {
	return &User{}
}

func (Users *Users) Add(entity model.Entity) {
	user := entity.(*User)
	*Users = append(*Users, *user)
}

func (user *User) getName() any {
	return (user.Name)
}

func (user *User) getEmail() any {
	return (user.Email)
}

func (user *User) getAddress() any {
	return (user.Address)
}

func (user *User) getCity() any {
	return (user.City)
}

func (user *User) getState() any {
	return (user.State)
}

func (user *User) getZip() any {
	return (user.Zip)
}

func (user *User) getBirthDate() any {
	return (user.BirthDate)
}

func (user *User) getLatitude() any {
	return (user.Latitude)
}

func (user *User) getLongitude() any {
	return (user.Longitude)
}

func (user *User) getPassword() any {
	return (user.Password)
}

func (user *User) getSource() any {
	return (user.Source)
}

func (user *User) getRole() any {
	return int32(user.Role)
}

func (user *User) NewEntity() model.Entity {
	return &User{}
}

func (user *User) EnumerateFields(f func(name string, value any)) {
	f("name", user.getName())
	f("email", user.getEmail())
	f("address", user.getAddress())
	f("city", user.getCity())
	f("state", user.getState())
	f("zip", user.getZip())
	f("birthDate", user.getBirthDate())
	f("latitude", user.getLatitude())
	f("longitude", user.getLongitude())
	f("password", user.getPassword())
	f("source", user.getSource())
	f("role", user.getRole())
}

type UserInput struct {
	Name      NullString
	Email     NullString
	Address   NullString
	City      NullString
	State     NullString
	Zip       NullString
	BirthDate NullDate
	Latitude  NullDouble
	Longitude NullDouble
	Password  NullString
	Source    NullString
	Role      NullInt
}

func (user *UserInput) NewEntity() model.Entity {
	return &User{}
}

func (user *UserInput) EnumerateFields(f func(name string, value any)) {
	if user.Name.State != None {
		f("name", user.Name)
	}
	if user.Email.State != None {
		f("email", user.Email)
	}
	if user.Address.State != None {
		f("address", user.Address)
	}
	if user.City.State != None {
		f("city", user.City)
	}
	if user.State.State != None {
		f("state", user.State)
	}
	if user.Zip.State != None {
		f("zip", user.Zip)
	}
	if user.BirthDate.State != None {
		f("birthDate", user.BirthDate)
	}
	if user.Latitude.State != None {
		f("latitude", user.Latitude)
	}
	if user.Longitude.State != None {
		f("longitude", user.Longitude)
	}
	if user.Password.State != None {
		f("password", user.Password)
	}
	if user.Source.State != None {
		f("source", user.Source)
	}
	if user.Role.State != None {
		f("role", user.Role)
	}
}
