package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"graphql-pro/domain/model"
	"graphql-pro/gql/dataloader"
)

// User is the resolver for the user field.
func (r *orderResolver) User(ctx context.Context, obj *model.Order) (*model.User, error) {
	loaders := dataloader.FromContext(ctx)
	if user, err := loaders.UserLoader.Load(ctx, obj.UserId); err != nil {
		return nil, err
	} else {
		return user, nil
	}
}

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

type orderResolver struct{ *Resolver }
