package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"graphql-project/domain/model"
	"graphql-project/tracing"
)

// Product is the resolver for the product field.
func (r *reviewResolver) Product(ctx context.Context, obj *model.Review) (*model.Product, error) {
	ctx, span := tracing.InitSpan(ctx, "/query/Review.Product")
	defer span.End()
	return r.productRepository.GetProductByID(ctx, obj.ProductId)
}

// Review returns ReviewResolver implementation.
func (r *Resolver) Review() ReviewResolver { return &reviewResolver{r} }

type reviewResolver struct{ *Resolver }
