package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"graphql-project/domain/model"
	"graphql-project/domain/repository"
	"graphql-project/gql/dataloader"
)

// Orders is the resolver for the orders field.
func (r *userResolver) Orders(ctx context.Context, obj *model.User, offset int32, limit int32) ([]model.Order, error) {
	loaders := dataloader.FromContext(ctx)
	if orders, err := loaders.UserOrdersLoader.Load(repository.With(ctx, offset, limit), obj.ID); err != nil {
		return nil, err
	} else {
		return orders, nil
	}
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
