// Code generated by gen; DO NOT EDIT.
package repository

import (
	"context"

	"graphql-project/domain/model"
	i "graphql-project/interface/model"
)

func (r *OrderRepository) GetOrderByID(ctx context.Context, id int64) (*model.Order, error) {
	var order model.Order
	err := FindEntity(ctx, (*DataSource)(r), &order, SelectById(ctx, id))
	if err != nil {
		return nil, err
	}
	return &order, nil
}

func (r *OrderRepository) GetOrders(ctx context.Context, offset int32, limit int32, sort model.Sort) ([]*model.Order, error) {
	orders := make([]*model.Order, 0, max(int(limit), 128))
	err := FindEntities(ctx, (*DataSource)(r), &model.Order{}, SelectMany(ctx, offset, limit, sort), func(ordinality int64, entity i.Entity) {
		orders = append(orders, entity.(*model.Order))
	})
	if err != nil {
		return nil, err
	}
	return orders, nil
}

func (r *OrderRepository) GetOrderByIds(ctx context.Context, ids []int64) ([]*model.Order, []error) {
	orders := make([]*model.Order, 0, len(ids))
	err := FindEntities(ctx, (*DataSource)(r), &model.Order{}, SelectByIds(ctx, ids), func(ordinality int64, entity i.Entity) {
		if entity.IsEmpty() {
			orders = append(orders, nil)
		} else {
			orders = append(orders, entity.(*model.Order))
		}
	})
	if err != nil {
		return nil, []error{err}
	}
	return orders, nil
}

func (r *OrderRepository) CreateOrder(ctx context.Context, inputOrder *model.Order) (*model.Order, error) {
	order, err := InsertEntity(ctx, (*DataSource)(r), inputOrder)
	if err != nil {
		return nil, err
	}
	return order.(*model.Order), err
}

func (r *OrderRepository) UpdateOrder(ctx context.Context, id int64, inputOrder *model.OrderInput) (*model.Order, error) {
	order, err := UpdateEntity(ctx, (*DataSource)(r), id, inputOrder)
	if err != nil {
		return nil, err
	}
	return order.(*model.Order), err
}

func NewOrderRepository(dataSource *DataSource) *OrderRepository {
	return (*OrderRepository)(dataSource)
}
