// Code generated by gen; DO NOT EDIT.
package repository

import (
	"context"

	"graphql-project/domain/model"
	i "graphql-project/interface/model"
)

func (r *ProductRepository) GetProductByID(ctx context.Context, id int64) (*model.Product, error) {
	var product model.Product
	err := FindEntity(ctx, (*DataSource)(r), &product, SelectById(ctx, id))
	if err != nil {
		return nil, err
	}
	return &product, nil
}

func (r *ProductRepository) GetProducts(ctx context.Context, offset int32, limit int32, sort model.Sort) ([]*model.Product, error) {
	products := make([]*model.Product, 0, max(int(limit), 128))
	err := FindEntities(ctx, (*DataSource)(r), &model.Product{}, SelectMany(ctx, offset, limit, sort), func(ordinality int64, entity i.Entity) {
		products = append(products, entity.(*model.Product))
	})
	if err != nil {
		return nil, err
	}
	return products, nil
}

func (r *ProductRepository) GetProductByIds(ctx context.Context, ids []int64) ([]*model.Product, []error) {
	products := make([]*model.Product, 0, len(ids))
	err := FindEntities(ctx, (*DataSource)(r), &model.Product{}, SelectByIds(ctx, ids), func(ordinality int64, entity i.Entity) {
		if entity.IsEmpty() {
			products = append(products, nil)
		} else {
			products = append(products, entity.(*model.Product))
		}
	})
	if err != nil {
		return nil, []error{err}
	}
	return products, nil
}

func (r *ProductRepository) CreateProduct(ctx context.Context, inputProduct *model.Product) (*model.Product, error) {
	product, err := InsertEntity(ctx, (*DataSource)(r), inputProduct)
	if err != nil {
		return nil, err
	}
	return product.(*model.Product), err
}

func (r *ProductRepository) UpdateProduct(ctx context.Context, id int64, inputProduct *model.ProductInput) (*model.Product, error) {
	product, err := UpdateEntity(ctx, (*DataSource)(r), id, inputProduct)
	if err != nil {
		return nil, err
	}
	return product.(*model.Product), err
}

func NewProductRepository(dataSource *DataSource) *ProductRepository {
	return (*ProductRepository)(dataSource)
}
