// Code generated by gen; DO NOT EDIT.
package repository

import (
	"context"

	"graphql-project/domain/model"
	i "graphql-project/interface/model"
)

func (r *ReviewRepository) GetReviewByID(ctx context.Context, id int64) (*model.Review, error) {
	var review model.Review
	err := FindEntity(ctx, (*DataSource)(r), &review, SelectById(ctx, id))
	if err != nil {
		return nil, err
	}
	return &review, nil
}

func (r *ReviewRepository) GetReviews(ctx context.Context, offset int32, limit int32, sort model.Sort) ([]*model.Review, error) {
	reviews := make([]*model.Review, 0, max(int(limit), 128))
	err := FindEntities(ctx, (*DataSource)(r), &model.Review{}, SelectMany(ctx, offset, limit, sort), func(ordinality int64, entity i.Entity) {
		if entity != nil {
			reviews = append(reviews, entity.(*model.Review))
		} else {
			reviews = append(reviews, nil)
		}
	})
	if err != nil {
		return nil, err
	}
	return reviews, nil
}

func (r *ReviewRepository) GetReviewByIds(ctx context.Context, ids []int64) ([]*model.Review, []error) {
	reviews := make([]*model.Review, 0, len(ids))
	err := FindEntities(ctx, (*DataSource)(r), &model.Review{}, SelectByIds(ctx, ids), func(ordinality int64, entity i.Entity) {
		if entity != nil {
			reviews = append(reviews, entity.(*model.Review))
		} else {
			reviews = append(reviews, nil)
		}
	})
	if err != nil {
		return nil, []error{err}
	}
	return reviews, nil
}

func (r *ReviewRepository) CreateReview(ctx context.Context, inputReview *model.Review) (*model.Review, error) {
	review, err := InsertEntity(ctx, (*DataSource)(r), inputReview)
	if err != nil {
		return nil, err
	}
	return review.(*model.Review), err
}

func (r *ReviewRepository) UpdateReview(ctx context.Context, id int64, inputReview *model.ReviewInput) (*model.Review, error) {
	review, err := UpdateEntity(ctx, (*DataSource)(r), id, inputReview)
	if err != nil {
		return nil, err
	}
	return review.(*model.Review), err
}

func NewReviewRepository(dataSource *DataSource) *ReviewRepository {
	return (*ReviewRepository)(dataSource)
}
