// Code generated by gen; DO NOT EDIT.
package repository

import (
	"context"

	"graphql-project/domain/model"
	i "graphql-project/interface/model"
)

func (r *UserRepository) GetUserByID(ctx context.Context, id int64) (*model.User, error) {
	var user model.User
	err := FindEntity(ctx, (*DataSource)(r), &user, SelectById(ctx, id))
	if err != nil {
		return nil, err
	}
	return &user, nil
}

func (r *UserRepository) GetUsers(ctx context.Context, offset int32, limit int32, sort model.Sort) ([]*model.User, error) {
	users := make([]*model.User, 0, max(int(limit), 128))
	err := FindEntities(ctx, (*DataSource)(r), &model.User{}, SelectMany(ctx, offset, limit, sort), func(ordinality int64, entity i.Entity) {
		users = append(users, entity.(*model.User))
	})
	if err != nil {
		return nil, err
	}
	return users, nil
}

func (r *UserRepository) GetUserByIds(ctx context.Context, ids []int64) ([]*model.User, []error) {
	users := make([]*model.User, 0, len(ids))
	err := FindEntities(ctx, (*DataSource)(r), &model.User{}, SelectByIds(ctx, ids), func(ordinality int64, entity i.Entity) {
		if entity.IsEmpty() {
			users = append(users, nil)
		} else {
			users = append(users, entity.(*model.User))
		}
	})
	if err != nil {
		return nil, []error{err}
	}
	return users, nil
}

func (r *UserRepository) CreateUser(ctx context.Context, inputUser *model.User) (*model.User, error) {
	user, err := InsertEntity(ctx, (*DataSource)(r), inputUser)
	if err != nil {
		return nil, err
	}
	return user.(*model.User), err
}

func (r *UserRepository) UpdateUser(ctx context.Context, id int64, inputUser *model.UserInput) (*model.User, error) {
	user, err := UpdateEntity(ctx, (*DataSource)(r), id, inputUser)
	if err != nil {
		return nil, err
	}
	return user.(*model.User), err
}

func NewUserRepository(dataSource *DataSource) *UserRepository {
	return (*UserRepository)(dataSource)
}
